# Generated by Django 3.1.5 on 2021-02-02 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='영상 내용 설명', max_length=500, null=True, verbose_name='설명')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='PWD')),
                ('age', models.PositiveIntegerField(verbose_name='나이')),
                ('gender', models.CharField(max_length=50, verbose_name='성별')),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi.video')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('re_id', models.AutoField(primary_key=True, serialize=False, verbose_name='리뷰등록번호')),
                ('re_title', models.CharField(max_length=120, verbose_name='리뷰 제목')),
                ('user_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi.user', verbose_name='작성자')),
            ],
        ),
    ]
